name: Build and test

on:
  push:
    branches: [ main, public ]
  pull_request:
    branches: [ main, public ]

jobs:
  build:
    runs-on: macos-13

    steps:
    - uses: actions/checkout@v2

    - name: Set up Swift environment
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.1'

    - name: Build with Swift
      run: swift build

    - name: Test with Swift
      run: swift test